version: '3'
services:
  frontend:
    build:
      context: ./client
    ports:
      - '80:80'
    depends_on:
      - backend
  backend:
    build:
      context: ./server
    ports:
      - '3001:3001'